[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "3499977893", # Advanced Developer Tools's Workshop ID
    "1638341685" # DUI Workshop ID
]

[melb]
extends = "default"
workshop = [
    "561177050", # MELB workshop id
]
